name: Release
on:
  workflow_call:
    inputs:
      version:
        description: The semantic version of the new release.
        required: true
        type: string
  workflow_dispatch: # Allows running this workflow for this repo
    inputs:
      version:
        description: The semantic version of the new release.
        required: true
        type: string
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Validate the new version
        run: |
          version=$(sed 's/^v//' <<<"${{inputs.version}}")
          [[ "${version}" =~ ^[0-9]+\.[0-9]+\.[0-9]$ ]]
          echo "version=${version}" >> ${GITHUB_ENV}
      - name: Clone the repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-tags: true
      - name: Tag the repository
        # Create the new vA.B.C tag, then update the vA.B tag, then update the
        # vA tag.
        run: |
          # git config user.name "GitHub Actions"
          # git config user.email "github-actions@users.noreply.github.com"
          git tag "v${version}"
          git tag --force "v$(sed 's/\.[0-1]*$//' <<<"${version}")"
          git tag --force "v$(sed 's/\.[0-1]*\.[0-1]*$//' <<<"${version}")"
      - name: Push the tags
        run: git push --tags --force
      - name: Create a release on GitHub
        env:
          GH_TOKEN: ${{github.token}}
        run: |
          gh auth login --git-protocol https --with-token <<<"${GH_TOKEN}"
          gh release create \
            --repo ${{github.repository}} \
            --target main \
            --title "${version}" \
            --notes "[Release Notes](/CHANGELOG.md)" \
            "v${version}"
